# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Release Artifacts

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build app bundle
      env:
        PYINSTALLER_TARGET_ARCH: universal2
      run: python Build-Project.command
    - name: Package artifacts
      run: |
        ditto -c -k --keepParent dist/OpenCore-Patcher.app OpenCore-Patcher.app.zip
        ditto -c -k --keepParent dist/OpenCore-Patcher.pkg OpenCore-Patcher.pkg.zip
        ditto -c -k --keepParent dist/OpenCore-Patcher-Uninstaller.pkg OpenCore-Patcher-Uninstaller.pkg.zip
        ditto -c -k --keepParent dist/AutoPkg-Assets.pkg AutoPkg-Assets.pkg.zip
    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencore-legacy-patcher-build
        retention-days: 7
        path: |
          OpenCore-Patcher.app.zip
          OpenCore-Patcher.pkg.zip
          OpenCore-Patcher-Uninstaller.pkg.zip
          AutoPkg-Assets.pkg.zip
    - name: Upload release assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OpenCore-Patcher.app.zip
          OpenCore-Patcher.pkg.zip
          OpenCore-Patcher-Uninstaller.pkg.zip
          AutoPkg-Assets.pkg.zip
